package br.com.cinepoti.cinepoti_api.mapper;

import br.com.cinepoti.cinepoti_api.model.Address;
import br.com.cinepoti.cinepoti_api.dto.request.AddressRequestDTO;
import br.com.cinepoti.cinepoti_api.dto.response.AddressResponseDTO;

public class AddressMapper {

    // Converts AddressRequestDTO to Address entity
    public static Address toEntity(AddressRequestDTO addressRequestDTO) {
        if (addressRequestDTO == null) {
            return null;
        }

        // Creating the Address entity from the AddressRequestDTO
        return new Address(
                null, // ID will be generated by the database
                addressRequestDTO.street(),
                addressRequestDTO.city(),
                addressRequestDTO.state(),
                addressRequestDTO.neighborhood(),
                addressRequestDTO.streetNumber(),
                addressRequestDTO.cep()
        );
    }

    // Converts Address entity to AddressResponseDTO
    public static AddressResponseDTO toResponseDTO(Address address) {
        if (address == null) {
            return null;
        }

        // Creating the AddressResponseDTO using data from the Address entity
        return new AddressResponseDTO(
                address.getId(),
                address.getStreet(),
                address.getCity(),
                address.getState(),
                address.getNeighborhood(),
                address.getStreetNumber(),
                address.getCep()
        );
    }
}
