package br.com.cinepoti.cinepoti_api.mapper;

import br.com.cinepoti.cinepoti_api.model.BookTicket;
import br.com.cinepoti.cinepoti_api.dto.request.BookTicketRequestDTO;
import br.com.cinepoti.cinepoti_api.dto.response.BookTicketResponseDTO;
import br.com.cinepoti.cinepoti_api.model.Booking;
import br.com.cinepoti.cinepoti_api.model.Exhibition;
import br.com.cinepoti.cinepoti_api.model.Seat;

public class BookTicketMapper {

    // Converts BookTicketRequestDTO to BookTicket entity
    public static BookTicket toEntity(BookTicketRequestDTO bookTicketRequestDTO, Booking booking, Seat seat, Exhibition exhibition) {
        if (bookTicketRequestDTO == null) {
            return null;
        }

        return new BookTicket(
                null, // ID will be generated by the database
                seat,
                booking,
                exhibition
        );
    }

    public static BookTicket toEntity(BookTicketRequestDTO bookTicketRequestDTO, Long bookingId, Long seatId, Long exhibitionId) {
        if (bookTicketRequestDTO == null) {
            return null;
        }

        return new BookTicket(
                null, // ID will be generated by the database
                seatId,
                bookingId,
                exhibitionId
        );
    }

    // Converts BookTicket entity to BookTicketResponseDTO
    public static BookTicketResponseDTO toResponseDTO(BookTicket bookTicket) {
        if (bookTicket == null) {
            return null;
        }

        return new BookTicketResponseDTO(
                bookTicket.getId(),
                bookTicket.getBooking(),
                bookTicket.getSeat()
        );
    }
}
