package br.com.cinepoti.cinepoti_api.mapper;

import br.com.cinepoti.cinepoti_api.model.CinemaRoom;
import br.com.cinepoti.cinepoti_api.model.Exhibition;
import br.com.cinepoti.cinepoti_api.dto.request.ExhibitionRequestDTO;
import br.com.cinepoti.cinepoti_api.dto.response.ExhibitionResponseDTO;
import br.com.cinepoti.cinepoti_api.model.Movie;

public class ExhibitionMapper {

    // Converts ExhibitionRequestDTO to Exhibition entity
    public static Exhibition toEntity(ExhibitionRequestDTO exhibitionRequestDTO, Movie movie, CinemaRoom cinemaRoom) {
        if (exhibitionRequestDTO == null) {
            return null;
        }

        return new Exhibition(
                null, // ID will be generated by the database
                exhibitionRequestDTO.startTime(),
                cinemaRoom,
                movie
        );
    }

    public static Exhibition toEntity(ExhibitionRequestDTO exhibitionRequestDTO) {
        if (exhibitionRequestDTO == null) {
            return null;
        }

        return new Exhibition(
                null, // ID will be generated by the database
                exhibitionRequestDTO.startTime(),
                exhibitionRequestDTO.cinemaRoomId(),
                exhibitionRequestDTO.movieId()
        );
    }

    // Converts Exhibition entity to ExhibitionResponseDTO
    public static ExhibitionResponseDTO toResponseDTO(Exhibition exhibition) {
        if (exhibition == null) {
            return null;
        }

        return new ExhibitionResponseDTO(
                exhibition.getId(),
                exhibition.getMovie(),
                exhibition.getCinemaRoom(),
                exhibition.getStartTime()
        );
    }
}
