package br.com.cinepoti.cinepoti_api.mapper;

import br.com.cinepoti.cinepoti_api.model.CinemaRoom;
import br.com.cinepoti.cinepoti_api.model.Seat;
import br.com.cinepoti.cinepoti_api.dto.request.SeatRequestDTO;
import br.com.cinepoti.cinepoti_api.dto.response.SeatResponseDTO;

public class SeatMapper {

    // Converts SeatRequestDTO to Seat entity
    public static Seat toEntity(SeatRequestDTO seatRequestDTO, CinemaRoom cinemaRoom) {
        if (seatRequestDTO == null) {
            return null;
        }

        return new Seat(
                null, // ID will be generated by the database
                seatRequestDTO.price(),
                cinemaRoom,
                seatRequestDTO.row(),
                seatRequestDTO.number()
        );
    }

    // Converts Seat entity to SeatResponseDTO
    public static SeatResponseDTO toResponseDTO(Seat seat) {
        if (seat == null) {
            return null;
        }

        return new SeatResponseDTO(
                seat.getId(),
                seat.getCinemaRoom().getId(),
                seat.getRow(),
                seat.getNumber(),
                seat.getPrice()
        );
    }
}
