package br.com.cinepoti.cinepoti_api.mapper;

import br.com.cinepoti.cinepoti_api.model.Ticket;
import br.com.cinepoti.cinepoti_api.dto.request.TicketRequestDTO;
import br.com.cinepoti.cinepoti_api.dto.response.TicketResponseDTO;
import br.com.cinepoti.cinepoti_api.model.Booking;
import br.com.cinepoti.cinepoti_api.model.Seat;

public class TicketMapper {

    // Converts TicketRequestDTO to Ticket entity
    public static Ticket toEntity(TicketRequestDTO TicketRequestDTO, Booking booking, Seat seat) {
        if (TicketRequestDTO == null) {
            return null;
        }

        return new Ticket(
                null, // ID will be generated by the database
                seat,
                booking
        );
    }

    // Converts Ticket entity to TicketResponseDTO
    public static TicketResponseDTO toResponseDTO(Ticket Ticket) {
        if (Ticket == null) {
            return null;
        }

        return new TicketResponseDTO(
                Ticket.getId(),
                Ticket.getBooking().getId(),
                Ticket.getSeat().getId()
        );
    }
}
